<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>imljson</string>
      <string>iml</string>
      <string>js</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(?x)^\s*[{\[](?!.*[}\]],?\s*$)|[{\[]\s*$</string>
    <key>foldingStopMarker</key>
    <string>(?x)^\s*[}\]]</string>
    <key>keyEquivalent</key>
    <string>^~J</string>
    <key>name</key>
    <string>IML</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#iml</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>iml</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#moustache</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#rpc</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#escapes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#plaintext</string>
          </dict>
        </array>
      </dict>
      <key>moustache</key>
      <dict>
        <key>begin</key>
        <string>{{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.generic.begin</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.generic.end</string>
          </dict>
        </dict>
        <!-- INSIDE MOUSTACHE -->
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#moustache-inside</string>
          </dict>
        </array>
      </dict>
      <key>moustache-inside</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#moustache-keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#moustache-keywords-alone</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#moustache-functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#moustache-singlestring</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#moustache-nomatch</string>
          </dict>
        </array>
      </dict>
      <key>moustache-keywords</key>
      <dict>
        <key>match</key>
        <string>((item|body|connection|parameters|response|headers|temp)\.)([\w\.]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.language</string>
          </dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.other.member</string>
          </dict>
        </dict>
      </dict>
      <key>moustache-keywords-alone</key>
      <dict>
        <key>match</key>
        <string>(item|body|connection|parameters|response|headers|temp|undefined)</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.language</string>
          </dict>
        </dict>
      </dict>
      <key>rpc</key>
      <dict>
        <key>match</key>
        <string>(rpc\:\/\/)(\w)+</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
      </dict>
      <key>escapes</key>
      <dict>
        <key>match</key>
        <string>(?x)\\(?:["\\/bfnrt{}]|u[0-9a-fA-F]{4})</string>
        <key>name</key>
        <string>constant.character.escape</string>
      </dict>
      <key>plaintext</key>
      <dict>
        <key>match</key>
        <string>([\w.!@#$%^&*()_+\-=\[\]; ':|,\/?]+)</string>
        <key>name</key>
        <string>string.quoted.double</string>
      </dict>
      <key>moustache-functions</key>
      <dict>
        <key>match</key>
        <string>(\w+)(\()(.+)?(\))</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.end</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.parens.begin</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#moustache-inside</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>moustache-singlestring</key>
      <dict>
        <key>match</key>
        <string>('(\S+)?')</string>
        <key>name</key>
        <string>string.quoted.single</string>
      </dict>
      <key>moustache-nomatch</key>
      <dict>
        <key>match</key>
        <string>(\w+)</string>
        <key>name</key>
        <string>string.unquoted</string>
      </dict>
      <!-- GLOBAL FUNCTION COLORIZER -->
      <!--
      <key>function</key>
      <dict>
        <key>match</key>
        <string>(\w+)(\()(.+)?(\))</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>function.iml.imlf.bracket</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>function.iml.imlf.name</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>function.iml.imlf.bracket</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#iml</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      -->
    </dict>
    <key>scopeName</key>
    <string>source.iml</string>
    <key>uuid</key>
    <string>8f97457b-516e-48ce-83c7-08ae12fb327a</string>
  </dict>
</plist>
